env_name: MinAtar/Asterix-v1
env_steps: 5_000_000
n_trials: 5
tensorboard: True
target_selection: False

algorithm: DQN

# Algorithm hyperparameters
batch_size: 32
buffer_size: 100_00
target_update: 1_000
train_freq: 1
warmup: 5000
learning_rate: 0.00025
gamma: 0.99