env_name: MinAtar/Breakout-v1
algorithm: DQN

# Algorithm hyperparameters
batch_size: 32
buffer_size: 100_000
target_update: 1_000  # 0.005 # >1 for hard updates, <1 for soft
train_freq: 1
warmup: 5000
learning_rate: 0.00025
gamma: 0.99

# Important part
target_selection: False